export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const TEST_CREATOR_START = 'TEST_CREATOR_START';
export const TEST_CREATOR_FAIL = 'TEST_CREATOR_FAIL';
export const TEST_CREATOR_SUCCESS = 'TEST_CREATOR_SUCCESS'

export const FETCH_TESTS_START = 'FETCH_TESTS_START';
export const FETCH_TESTS_FAIL = 'FETCH_TESTS_FAIL';
export const FETCH_TESTS_SUCCESS = 'FETCH_TESTS_SUCCESS'

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';